### ISSUE TITLE
Missing OpenMP support?

### ISSUE THREAD

**Issue by dev-zero** [fortesg/fortrancallgraph#17]
I am trying to use FCG on https://github.com/cp2k/cp2k/blob/master/src/hfx_energy_potential.F and everything inside the OMP-parallel section inside the `integrate_four_center` routine seems to be missing. Are OpenMP-directives supported?

**Comment by chovyy** [comment]
Generally, there is a basic support for OpenMP but I cannot guarantee that it works 100%, it might not as it seems. I'm trying to figure out what is going on there but this subroutine is really huge, so it won't be easy. It would help me a lot if you can build a smaller example that also doesn't work.

**Comment by chovyy** [comment]
@dev-zero, can you please try with new release [v1.8.4](https://github.com/fortesg/fortrancallgraph/releases/tag/v1.8.4)!

**Comment by dev-zero** [comment]
@chovyy yes, that works. Thank you very much!
